### ISSUE TITLE
Non obvious error if chipshouter not connected

### ISSUE THREAD

**Issue by nicastellanos** [newaetech/ChipSHOUTER-python#2]
If CS isn't connected, printing cs object gives you:

    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "chipshouter.py", line 839, in __repr__
        return dict_to_str(self._dict_repr())
      File "chipshouter.py", line 827, in _dict_repr
        dict['absentTemp']          = self.absentTemp
    AttributeError: 'ChipSHOUTER' object has no attribute 'absentTemp'

**Comment by nicastellanos** [comment]
Issue came from
